### PR TITLE
Updates for latest Julia 0.7

### LINKED ISSUE #66: Error accessing attribute (Julia 0.7-alpha)
On Julia 0.7-alpha:

```julia
julia> doc = EzXML.parsexml("""
       <primates>
           <genus name="Homo">
               <species name="sapiens">Human</species>
           </genus>
           <genus name="Pan">
               <species name="paniscus">Bonobo</species>
               <species name="troglodytes">Chimpanzee</species>
           </genus>
       </primates>
       """)

julia> el = first(find(doc, "//genus"))
EzXML.Node(<ELEMENT_NODE@0x00007f8370da8130>)

julia> el["name"]
ERROR: MethodError: no method matching -(::Nothing, ::Int64)
Closest candidates are:
  -(::Complex{Bool}, ::Real) at complex.jl:297
  -(::Missing, ::Number) at missing.jl:90
  -(::Base.CoreLogging.LogLevel, ::Any) at logging.jl:107
  ...
Stacktrace:
 [1] getindex(::Main.EzXML.Node, ::String) at /Users/omus/.julia/dev/EzXML/src/node.jl:1145
 [2] top-level scope
```

### PR DESCRIPTION
**Pull request by ararslan**
Summary of changes:

* Use `something` instead of `coalesce`. Fixes #66.

* Add 0.7-alpha testing to the CI setup.

### CODE REVIEW

**Comment by ararslan** [comment]
The Linux failures look like an issue with BinaryProvider. @staticfloat, have you seen anything like that?

**Comment by staticfloat** [comment]
No, I haven't.  Looks like a problem with your built binaries.  Have yuo
tried downloading them locally to see if they work?

**Comment by ararslan** [comment]
Oh yeah, I can confirm locally on Linux that they don't work:
```
julia> Pkg.add("EzXML")
INFO: Cloning cache of EzXML from https://github.com/bicycle1885/EzXML.jl.git
INFO: Installing EzXML v0.6.3
INFO: Building EzXML
Info: Directory /home/alex/.julia/v0.6/EzXML/deps/usr/lib does not exist!
Info: Downloading https://github.com/bicycle1885/XML2Builder/releases/download/v1.0.0/XML2Builder.x86_64-linux-gnu.tar.gz to /home/alex/.julia/v0.6/EzXML/deps/usr/downloads/XML2Builder.x86_64-linux-gnu.tar.gz...
[15:36:34] ######################################################################## 100.0%
Info: No hash cache found
Info: Calculated hash d3125723e5c75ded1eb01e5ce06c7dfae149ee276aa2d3f82a64edb2e8df23b8 for file /home/alex/.julia/v0.6/EzXML/deps/usr/downloads/XML2Builder.x86_64-linux-gnu.tar.gz
Info: Installing /home/alex/.julia/v0.6/EzXML/deps/usr/downloads/XML2Builder.x86_64-linux-gnu.tar.gz into /home/alex/.julia/v0.6/EzXML/deps/usr
Inconsistency detected by ld.so: dl-version.c: 224: _dl_check_map_versions: Assertion `needed != NULL' failed!
ERROR: Build process failed.
build!(::Array{String,1}, ::Set{Any}, ::String) at ./pkg/entry.jl:629
build!(::Array{String,1}, ::Dict{Any,Any}, ::Set{Any}) at ./pkg/entry.jl:637
build(::Array{String,1}) at ./pkg/entry.jl:652
resolve(::Dict{String,Base.Pkg.Types.VersionSet}, ::Dict{String,Dict{VersionNumber,Base.Pkg.Types.Available}}, ::Dict{String,Tuple{VersionNumber,Bool}}, ::Dict{String,Base.Pkg.Types.Fixed}, ::Dict{String,VersionNumber}, ::Set{String}) at ./pkg/entry.jl:572
resolve(::Dict{String,Base.Pkg.Types.VersionSet}, ::Dict{String,Dict{VersionNumber,Base.Pkg.Types.Available}}, ::Dict{String,Tuple{VersionNumber,Bool}}, ::Dict{String,Base.Pkg.Types.Fixed}) at ./pkg/entry.jl:479
edit(::Function, ::String, ::Base.Pkg.Types.VersionSet, ::Vararg{Base.Pkg.Types.VersionSet,N} where N) at ./pkg/entry.jl:30
(::Base.Pkg.Entry.##1#3{String,Base.Pkg.Types.VersionSet})() at ./task.jl:335
Stacktrace:
 [1] sync_end() at ./task.jl:287
 [2] macro expansion at ./task.jl:303 [inlined]
 [3] add(::String, ::Base.Pkg.Types.VersionSet) at ./pkg/entry.jl:51
 [4] (::Base.Pkg.Dir.##4#7{Array{Any,1},Base.Pkg.Entry.#add,Tuple{String}})() at ./pkg/dir.jl:36
 [5] cd(::Base.Pkg.Dir.##4#7{Array{Any,1},Base.Pkg.Entry.#add,Tuple{String}}, ::String) at ./file.jl:70
 [6] #cd#1(::Array{Any,1}, ::Function, ::Function, ::String, ::Vararg{Any,N} where N) at ./pkg/dir.jl:36
 [7] add(::String) at ./pkg/pkg.jl:117
```

**Comment by felipenoris** [comment]
See #64 and #65.

**Comment by Alexander-Barth** [comment]
In order to check if there is something wrong with the so file, I have tried the library with python's ctype interface, and they seem to work:

```python
from ctypes import *
lib  = cdll.LoadLibrary("/tmp/XML/lib/libxml2.so")
doc = lib.xmlParseFile(c_char_p(b"/etc/cupshelpers/preferreddrivers.xml"))
cur = lib.xmlDocGetRootElement(doc)
print(cur)
```

This error also affects Julia 0.6.3. In Julia 0.6.3 I get immediately this error (as reported also for Julia 0.7):
```
julia> Libdl.dlopen("/tmp/XML/lib/libxml2.so")
Inconsistency detected by ld.so: dl-version.c: 224: _dl_check_map_versions: Assertion `needed != NULL' failed!
```
I do not have this issue with the system version of libxml2 or on Julia 0.6.2

```julia
julia> Libdl.dlopen("/usr/lib/x86_64-linux-gnu/libxml2.so")
Ptr{Void} @0x0000000003f74540
```
(I noticed that julia 0.6.2 depends on my system version of libz.so, but this is not the case for julia 0.6.3. I don't now if this is related )

**Comment by Alexander-Barth** [comment]
A custom compiled version of libxml2 2.9.7 (same version as the provided binary) works on Julia 0.6.3 and Julia 0.7 (version 0.7.0-alpha.0 (2018-05-31 00:07 UTC)):

```
julia> Libdl.dlopen(expanduser("~/opt/libxml2-2.9.7/lib/libxml2.so"))
WARNING: Base.Libdl is deprecated, run `using Libdl` instead
 in module Main
Ptr{Nothing} @0x00000000014315c0

julia> Libdl.dlopen("/tmp/XML/lib/libxml2.so")
WARNING: Base.Libdl is deprecated, run `using Libdl` instead
 in module Main
Ptr{Nothing} @0x0000000001411280
```

What is also strange, is that a subsequent load of the problematic libxml2.so library succeeds.

**Comment by staticfloat** [comment]
> What is also strange, is that a subsequent load of the problematic libxml2.so library succeeds.

This is because the dynamic linker already knows that a `libxml2.so` is loaded, so trying to load it again is a no-op.  You'll get a different handle, but if you `Libdl.dlpath()` that handle, you'll find it is pointing back at the first file.

**Comment by Alexander-Barth** [comment]
> You'll get a different handle, but if you Libdl.dlpath() that handle, you'll find it is pointing back at the first file.

For what it is worth I tried this on my machine, and this is what I get:
```julia
using Libdl
# locally compiled version
Libdl.dlpath(Libdl.dlopen(expanduser("~/opt/libxml2-2.9.7/lib/libxml2.so")))
# returns "/home/abarth/opt/libxml2-2.9.7/lib/libxml2.so"
# binary provided by EzXML
Libdl.dlpath(Libdl.dlopen(expanduser("/media/abarth/9982a2e8-599f-4b37-884f-a59aa1c0de80/Alex/XML2Builder.x86_64-linux-gnu/lib/libxml2.so")))
# returns "/media/abarth/9982a2e8-599f-4b37-884f-a59aa1c0de80/Alex/XML2Builder.x86_64-linux-gnu/lib/libxml2.so"
```

I tried to rebuild also libz and libxml2 with the same build steps as here (https://github.com/bicycle1885/XML2Builder/blob/master/build_tarballs.jl):

```bash
wget https://zlib.net/zlib-1.2.11.tar.gz
wget ftp://xmlsoft.org/libxml2/libxml2-2.9.7.tar.gz
tar xf zlib-1.2.11.tar.gz 
tar xf libxml2-2.9.7.tar.gz 
PREFIX=/media/abarth/9982a2e8-599f-4b37-884f-a59aa1c0de80/Alex/my-libxml2
cd zlib-1.2.11/
./configure --prefix=$PREFIX
make install
cd ../libxml2-2.9.7/
./configure --prefix=$PREFIX --without-python --with-zlib=$PREFIX
make install
```

And I could load it successfully:

```julia
 using Libdl; Libdl.dlopen(expanduser("/media/abarth/9982a2e8-599f-4b37-884f-a59aa1c0de80/Alex/my-libxml2/lib/libxml2.so"))
# returns Ptr{Nothing} @0x00000000017580d0
```

The only notable difference I see between my binary and the one build on travis is the Ubuntu version (I use 16.04 and travis CI 14.04). Does somebody known if there has been a change in the build environment between julia 0.6.2 and julia 0.6.3 / julia 0.7 ?

**Comment by staticfloat** [comment]
> For what it is worth I tried this on my machine, and this is what I get:

I stand corrected!  You're absolutely right; Julia namespaces things such that this doesn't happen.  That's my mistake.  I was confusing this with the typical system linker, not Julia's `Libdl`.  :)  That being said, the thing freaking out here is the system linker, not Julia.

I just tried building the builder repository locally (well, I used [this PR](https://github.com/bicycle1885/XML2Builder/pull/5)), and it built libraries that I can `dlopen()` no problem.  The important difference is, I believe, that we don't generate the funky RPATHs anymore that look like `::.`.  That seems to trigger a bug in some dl loading code.  (I should note that this only happens on 0.7 for me, not on 0.6, which is interesting; that might point to the bug actually being a _new_ one in some dynamic loading code in glibc, for instance).

In any case, I believe the solution here is to build a new set of binaries after [this PR](https://github.com/bicycle1885/XML2Builder/pull/5) gets merged, then re-run the CI here pointing to the new binaries.

**Comment by RalphAS** [comment]
@ararslan could you trigger a new Travis build, as at-staticfloat suggests above?  This package is blocking some other progress towards 0.7, so it would be great to finish this PR.

**Comment by bicycle1885** [comment]
Rebasing this onto the latest master will solve the problem of binaries.

**Comment by ararslan** [comment]
Rebased.

**Comment by bicycle1885** [comment]
Thank you!

**Comment by ararslan** [comment]
My pleasure! Could you tag a new patch release with this change?

**Pull request merged**
