### PR TITLE
return an empty node set when xpath expression doesn't match

### PR DESCRIPTION
**Pull request by clarkevans**

### CODE REVIEW

**Comment by bicycle1885** [comment]
Could you show me any examples that will cause a problem?

**Comment by bicycle1885** [comment]
For example, the following example does not fail even though there is no matching nodes for a query:

```
julia> doc = parsexml("""<root/>""")
EzXML.Document(EzXML.Node(<DOCUMENT_NODE@0x00007fc53d7e9b10>))

julia> find(doc, "//notexit")
0-element Array{EzXML.Node,1}

```

**Comment by bicycle1885** [comment]
Thank you. I've quickly checked libxml2 and found the following macro in xpath.h:
```c
/**
 * xmlXPathNodeSetIsEmpty:
 * @ns: a node-set
 *
 * Checks whether @ns is empty or not.
 *
 * Returns %TRUE if @ns is an empty node-set.
 */
#define xmlXPathNodeSetIsEmpty(ns)                                      \
    (((ns) == NULL) || ((ns)->nodeNr == 0) || ((ns)->nodeTab == NULL))

```

So, your patch looks good to me 👍 .

**Comment by Osirisxblack** [comment]
👌

**Pull request merged**
