### PR TITLE
Printing imported names

### PR DESCRIPTION
**Pull request by YongHee-Kim**
is this what you want for #78? 

``` julia
using EzXML
    docstr = """
    <?xml version="1.0" encoding="UTF-8"?>
    <root>
        <foo>ok</foo>
    </root>
    """
doc = parsexml(docstr)
show(doc)
> EzXML.Document(EzXML.Node(<DOCUMENT_NODE@0x000000001014d320>))

import EzXML.Node
show(doc)
> EzXML.Document(Node(<DOCUMENT_NODE@0x000000001014d320>))
```

### CODE REVIEW

**Comment by bicycle1885** [comment]
Cool! This is the thing what I wanted.

Can you add a similar method to the `Document` type?

**Comment by YongHee-Kim** [comment]
Yeah but you've only overridden `Base.show` function for 'Node' and 'StreamReader' type. 
So it `Document` is already working like this on '0.7.0' 😃 
```julia
using EzXML
import EzXML.Document

show(doc)
> Document(EzXML.Node(<DOCUMENT_NODE@0x0000000027c375f0>))
```

**Comment by bicycle1885** [comment]
Oops, you're right.

**Comment by bicycle1885** [comment]
Thank you for your pull request :)

**Comment by YongHee-Kim** [comment]
Happy to be helpful:) Thank you for great package!

**Pull request merged**
