### PR TITLE
New binaries (fixes #64 and #65)

### LINKED ISSUE #64: build failure on julia 0.7
On today julia master I see this
```julia
(v0.7) pkg> build EzXML
  Building EzXML → `~/.julia/packages/EzXML/Ns7p/deps/build.log`
┌ Error: Error building `EzXML`; see log file for further info
└ @ Pkg.Operations Operations.jl:866
```
The content of the log is
```
Inconsistency detected by ld.so: dl-version.c: 205: _dl_check_map_versions: Assertion `needed != NULL' failed!
```

### PR DESCRIPTION
**Pull request by felipenoris**

### CODE REVIEW

**Comment by bicycle1885** [comment]
I've rebuilt binary files on top of <https://github.com/bicycle1885/XML2Builder/pull/5>, which resolves a dependency problem on ZlibBuilder. So, could you update this pull request to make EzXML.jl download binary files from <https://github.com/bicycle1885/XML2Builder/releases/tag/v1.0.1>?

**Comment by felipenoris** [comment]
Sure! There you go.

**Comment by felipenoris** [comment]
For some reason, the package builds, but the tests fail due to XML parsing.

**Comment by bicycle1885** [comment]
Uh, this kind of error happens when libxml2 could not find zlib when building binaries:
```
XML: Error During Test
  Test threw an exception of type EzXML.XMLError
  Expression: readxml(compressed) isa EzXML.Document
  XMLError: Start tag expected, '<' not found from XML parser (code: 4, line: 1)
  Stacktrace:
   [1] throw_xml_error() at /home/travis/.julia/v0.6/EzXML/src/error.jl:87
   [2] macro expansion at /home/travis/.julia/v0.6/EzXML/src/error.jl:52 [inlined]
   [3] readxml(::String) at /home/travis/.julia/v0.6/EzXML/src/document.jl:141
   [4] macro expansion at /home/travis/.julia/v0.6/EzXML/test/runtests.jl:48 [inlined]
   [5] macro expansion at ./test.jl:860 [inlined]
   [6] macro expansion at /home/travis/.julia/v0.6/EzXML/test/runtests.jl:35 [inlined]
   [7] macro expansion at ./test.jl:860 [inlined]
   [8] anonymous at ./<missing>:?
```

Maybe this `--with-zlib` option is wrong: https://github.com/bicycle1885/XML2Builder/blob/0c18578e9d81d6fa725794775caeec72d194b9ff/build_tarballs.jl#L13

**Comment by bicycle1885** [comment]
Now I'm re-building binaries of libxml2. When they show up in <https://github.com/bicycle1885/XML2Builder/releases/tag/v1.0.1>, please update this pull request and re-run CI  to check the validity.

**Comment by bicycle1885** [comment]
Superseded by #69.

**Pull request closed without merging**
